### ISSUE TITLE
Process.py missing?

### ISSUE THREAD

**Issue by TheodoreGalanos** [SamLynnEvans/Transformer#1]
Hi I was wondering if there is a Process.py missing in your code. It seems to be imported, and a couple of functions rely on it (read_data perhaps?) but I can't seem to find it.

I hope this is what is going on and I haven't missed smth blatantly obvious!

Thanks for sharing the code!

Regards,
Theodore.

**Comment by SamLynnEvans** [comment]
Oh wow you're right! Just uploaded the file now. Thanks for pointing that out.
